# Generated by Django 4.1.3 on 2022-11-12 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snackbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShavedIce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.icecreamflavor')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
