# Generated by Django 4.1.3 on 2022-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shavedice',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snackbar',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
